---
- name: Ensure folder exists
  loop: "{{ dfsr_folders }}"
  ansible.windows.win_file:
    path: "{{ item.path }}"
    state: directory
  loop_control:
    label: "{{ item.path }}"

- name: Create DFS Replication Group
  throttle: 1
  ansible.windows.win_dsc:
    resource_name: DFSReplicationGroup
    GroupName: "{{ dfsr_replication_group_name }}"
    Ensure: Present
    Folders: "{{ _dfsr_folder_names }}"
    Members: "{{ dfsr_members }}"
    Topology: Fullmesh
    PSDSCRunAsCredential_username: "{{ dfsr_admin_user }}"
    PSDSCRunAsCredential_password: "{{ dfsr_admin_password }}"

- name: Configure DFS Replication Folder
  loop: "{{ dfsr_folders }}"
  ansible.windows.win_dsc:
    resource_name: DFSReplicationGroupFolder
    GroupName: "{{ dfsr_replication_group_name }}"
    FolderName: "{{ item.name }}"
  loop_control:
    label: "{{ item.name }}"

- name: Configure DFS Replication Group Membership
  loop: "{{ dfsr_folders }}"
  ansible.windows.win_dsc:
    resource_name: DFSReplicationGroupMembership
    GroupName: "{{ dfsr_replication_group_name }}"
    FolderName: "{{ item.name }}"
    ComputerName: "{{ inventory_hostname | upper }}"
    ContentPath: "{{ item.path }}"
    PrimaryMember: "{{ item.primary_member | default(dfsr_primary_member | default(omit)) }}"
    ReadOnly: "{{ item.read_only | default(dfsr_read_only | default(omit)) }}"
    StagingPathQuotaInMB: "{{ item.staging_quota | default(omit) }}"
    PSDSCRunAsCredential_username: "{{ dfsr_admin_user }}"
    PSDSCRunAsCredential_password: "{{ dfsr_admin_password }}"
  notify:
    - _dfsr_restart_dfsr
  loop_control:
    label: "{{ item.name }}"
