---
- name: Prepare DC
  hosts: dc
  roles:
    - role: trippsc2.create_testing_ad_domain

- name: Prepare member server
  hosts:
    - windows_domain_members
  gather_facts: false
  roles:
    - role: trippsc2.join_testing_ad_domain
  tasks:
    - name: Create replicated folders
      loop: "{{ dfsr_folders | map(attribute='path') }}"
      ansible.windows.win_file:
        path: "{{ item }}"
        state: directory

- name: Create test file for replication on primary
  hosts:
    - fs1
  tasks:
    - name: Create file
      ansible.windows.win_file:
        path: C:\Replica1\test.txt
        state: touch

- name: Create test file for replication on non-primary
  hosts:
    - fs2
  tasks:
    - name: Create file
      ansible.windows.win_file:
        path: C:\Replica2\test.txt
        state: touch
